
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class HomeMainCityTaskConfig : Luban.BeanBase
    {
        public HomeMainCityTaskConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["TaskGroupId"].IsNumber) { throw new SerializationException(); }  TaskGroupId = _buf["TaskGroupId"]; }
            { if(!_buf["TaskType"].IsNumber) { throw new SerializationException(); }  TaskType = _buf["TaskType"]; }
            { if(!_buf["Param1"].IsNumber) { throw new SerializationException(); }  Param1 = _buf["Param1"]; }
            { if(!_buf["Param2"].IsNumber) { throw new SerializationException(); }  Param2 = _buf["Param2"]; }
            { if(!_buf["Title"].IsString) { throw new SerializationException(); }  Title = _buf["Title"]; }
            { if(!_buf["Desc"].IsString) { throw new SerializationException(); }  Desc = _buf["Desc"]; }
            { if(!_buf["SortOrder"].IsNumber) { throw new SerializationException(); }  SortOrder = _buf["SortOrder"]; }

            EndInit();
        }

        public static HomeMainCityTaskConfig DeserializeHomeMainCityTaskConfig(JSONNode _buf)
        {
            return new ET.HomeMainCityTaskConfig(_buf);
        }

        public readonly int Id;
        public readonly int TaskGroupId;
        public readonly int TaskType;
        public readonly int Param1;
        public readonly int Param2;
        public readonly string Title;
        public readonly string Desc;
        public readonly int SortOrder;

        public const int __ID__ = -364305783;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "TaskGroupId:" + TaskGroupId + ","
            + "TaskType:" + TaskType + ","
            + "Param1:" + Param1 + ","
            + "Param2:" + Param2 + ","
            + "Title:" + Title + ","
            + "Desc:" + Desc + ","
            + "SortOrder:" + SortOrder + ","
            + "}";
        }

        partial void EndRef();
    }

}

