
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class HomeBuildingLevelConfig : Luban.BeanBase
    {
        public HomeBuildingLevelConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            BuildingConfigId = _buf.ReadInt();
            Level = _buf.ReadInt();
            UpgradeGoldCost = _buf.ReadInt();
            CapacityValue1 = _buf.ReadInt();
            CapacityValue2 = _buf.ReadInt();
            OutputValue = _buf.ReadInt();
            ExtraParams = _buf.ReadString();

            EndInit();
        }

        public static HomeBuildingLevelConfig DeserializeHomeBuildingLevelConfig(ByteBuf _buf)
        {
            return new ET.HomeBuildingLevelConfig(_buf);
        }

        public readonly int Id;
        public readonly int BuildingConfigId;
        public readonly int Level;
        public readonly int UpgradeGoldCost;
        public readonly int CapacityValue1;
        public readonly int CapacityValue2;
        public readonly int OutputValue;
        public readonly string ExtraParams;
    
        public const int __ID__ = 971388116;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "BuildingConfigId:" + BuildingConfigId + ","
            + "Level:" + Level + ","
            + "UpgradeGoldCost:" + UpgradeGoldCost + ","
            + "CapacityValue1:" + CapacityValue1 + ","
            + "CapacityValue2:" + CapacityValue2 + ","
            + "OutputValue:" + OutputValue + ","
            + "ExtraParams:" + ExtraParams + ","
            + "}";
        }

        partial void EndRef();
    }

}

