
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class MatchRobotConfig : Luban.BeanBase
    {
        public MatchRobotConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            MapName = _buf.ReadString();
            GameMode = _buf.ReadInt();
            AIBuffConfigId = _buf.ReadInt();
            HeroConfigIds = _buf.ReadString();
            HeroWeights = _buf.ReadString();
            MainWeaponConfigIds = _buf.ReadString();
            MainWeaponWeights = _buf.ReadString();
            AutoChooseDelayMinMs = _buf.ReadInt();
            AutoChooseDelayMaxMs = _buf.ReadInt();

            EndInit();
        }

        public static MatchRobotConfig DeserializeMatchRobotConfig(ByteBuf _buf)
        {
            return new ET.MatchRobotConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 地图名（空=通用）
        /// </summary>
        public readonly string MapName;
        /// <summary>
        /// 游戏模式（0=通用）
        /// </summary>
        public readonly int GameMode;
        /// <summary>
        /// 机器人AI BuffId
        /// </summary>
        public readonly int AIBuffConfigId;
        /// <summary>
        /// 可随机英雄配置（|分隔）
        /// </summary>
        public readonly string HeroConfigIds;
        /// <summary>
        /// 英雄权重（|分隔）
        /// </summary>
        public readonly string HeroWeights;
        /// <summary>
        /// 可随机主武器配置（|分隔）
        /// </summary>
        public readonly string MainWeaponConfigIds;
        /// <summary>
        /// 主武器权重（|分隔）
        /// </summary>
        public readonly string MainWeaponWeights;
        /// <summary>
        /// 自动选项最小延迟毫秒
        /// </summary>
        public readonly int AutoChooseDelayMinMs;
        /// <summary>
        /// 自动选项最大延迟毫秒
        /// </summary>
        public readonly int AutoChooseDelayMaxMs;
    
        public const int __ID__ = -493943098;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "MapName:" + MapName + ","
            + "GameMode:" + GameMode + ","
            + "AIBuffConfigId:" + AIBuffConfigId + ","
            + "HeroConfigIds:" + HeroConfigIds + ","
            + "HeroWeights:" + HeroWeights + ","
            + "MainWeaponConfigIds:" + MainWeaponConfigIds + ","
            + "MainWeaponWeights:" + MainWeaponWeights + ","
            + "AutoChooseDelayMinMs:" + AutoChooseDelayMinMs + ","
            + "AutoChooseDelayMaxMs:" + AutoChooseDelayMaxMs + ","
            + "}";
        }

        partial void EndRef();
    }

}

