
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson.Serialization.Options;

namespace ET
{

    /// <summary>
    /// 导航防穿墙参数配置
    /// </summary>
    [ConfigProcess(ConfigType.Luban)]
    public partial class NavmeshGuardConfigCategory : Singleton<NavmeshGuardConfigCategory>, IConfig
    {

        private readonly ET.NavmeshGuardConfig _data;

        public ET.NavmeshGuardConfig Data => _data;

        public NavmeshGuardConfigCategory(ByteBuf _buf)
        {
            int n = _buf.ReadSize();
            if (n != 1) throw new SerializationException("table mode=one, but size != 1");
            _data = global::ET.NavmeshGuardConfig.DeserializeNavmeshGuardConfig(_buf);
			EndInit();
        }


        /// <summary>
        /// ID
        /// </summary>
        public int Id => _data.Id;
        /// <summary>
        /// 移动投影半径XZ
        /// </summary>
        public float MovementProjectHalfExtentXZ => _data.MovementProjectHalfExtentXZ;
        /// <summary>
        /// 移动投影半径Y
        /// </summary>
        public float MovementProjectHalfExtentY => _data.MovementProjectHalfExtentY;
        /// <summary>
        /// 移动投影半径按角色系数
        /// </summary>
        public float MovementProjectHalfExtentByRadius => _data.MovementProjectHalfExtentByRadius;
        /// <summary>
        /// 摇杆偏差阈值
        /// </summary>
        public float MovementRejectDistance => _data.MovementRejectDistance;
        /// <summary>
        /// 摇杆偏差阈值按角色系数
        /// </summary>
        public float MovementRejectDistanceByRadius => _data.MovementRejectDistanceByRadius;
        /// <summary>
        /// 寻路吸附偏差阈值
        /// </summary>
        public float FindNearestRejectDistance => _data.FindNearestRejectDistance;
        /// <summary>
        /// 寻路吸附偏差阈值按角色系数
        /// </summary>
        public float FindNearestRejectDistanceByRadius => _data.FindNearestRejectDistanceByRadius;
        /// <summary>
        /// 最小角色半径
        /// </summary>
        public float MinUnitRadius => _data.MinUnitRadius;
        
        public void ResolveRef()
        {
            _data.ResolveRef();
            EndRef();
        }

        partial void EndRef();
    }

}

