
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class NavmeshGuardConfig : Luban.BeanBase
    {
        public NavmeshGuardConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            MovementProjectHalfExtentXZ = _buf.ReadFloat();
            MovementProjectHalfExtentY = _buf.ReadFloat();
            MovementProjectHalfExtentByRadius = _buf.ReadFloat();
            MovementRejectDistance = _buf.ReadFloat();
            MovementRejectDistanceByRadius = _buf.ReadFloat();
            FindNearestRejectDistance = _buf.ReadFloat();
            FindNearestRejectDistanceByRadius = _buf.ReadFloat();
            MinUnitRadius = _buf.ReadFloat();

            EndInit();
        }

        public static NavmeshGuardConfig DeserializeNavmeshGuardConfig(ByteBuf _buf)
        {
            return new ET.NavmeshGuardConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 移动投影半径XZ
        /// </summary>
        public readonly float MovementProjectHalfExtentXZ;
        /// <summary>
        /// 移动投影半径Y
        /// </summary>
        public readonly float MovementProjectHalfExtentY;
        /// <summary>
        /// 移动投影半径按角色系数
        /// </summary>
        public readonly float MovementProjectHalfExtentByRadius;
        /// <summary>
        /// 摇杆偏差阈值
        /// </summary>
        public readonly float MovementRejectDistance;
        /// <summary>
        /// 摇杆偏差阈值按角色系数
        /// </summary>
        public readonly float MovementRejectDistanceByRadius;
        /// <summary>
        /// 寻路吸附偏差阈值
        /// </summary>
        public readonly float FindNearestRejectDistance;
        /// <summary>
        /// 寻路吸附偏差阈值按角色系数
        /// </summary>
        public readonly float FindNearestRejectDistanceByRadius;
        /// <summary>
        /// 最小角色半径
        /// </summary>
        public readonly float MinUnitRadius;
    
        public const int __ID__ = -256367018;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "MovementProjectHalfExtentXZ:" + MovementProjectHalfExtentXZ + ","
            + "MovementProjectHalfExtentY:" + MovementProjectHalfExtentY + ","
            + "MovementProjectHalfExtentByRadius:" + MovementProjectHalfExtentByRadius + ","
            + "MovementRejectDistance:" + MovementRejectDistance + ","
            + "MovementRejectDistanceByRadius:" + MovementRejectDistanceByRadius + ","
            + "FindNearestRejectDistance:" + FindNearestRejectDistance + ","
            + "FindNearestRejectDistanceByRadius:" + FindNearestRejectDistanceByRadius + ","
            + "MinUnitRadius:" + MinUnitRadius + ","
            + "}";
        }

        partial void EndRef();
    }

}

