
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class RobotAutoLevelConfig : Luban.BeanBase
    {
        public RobotAutoLevelConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["TimeSec"].IsNumber) { throw new SerializationException(); }  TimeSec = _buf["TimeSec"]; }
            { if(!_buf["Level"].IsNumber) { throw new SerializationException(); }  Level = _buf["Level"]; }

            EndInit();
        }

        public static RobotAutoLevelConfig DeserializeRobotAutoLevelConfig(JSONNode _buf)
        {
            return new ET.RobotAutoLevelConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 局内经过秒数
        /// </summary>
        public readonly int TimeSec;
        /// <summary>
        /// 目标等级
        /// </summary>
        public readonly int Level;

        public const int __ID__ = 1535760108;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "TimeSec:" + TimeSec + ","
            + "Level:" + Level + ","
            + "}";
        }

        partial void EndRef();
    }

}

