
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class RogueKillExpEntryConfig : Luban.BeanBase
    {
        public RogueKillExpEntryConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["UnitType"].IsNumber) { throw new SerializationException(); }  UnitType = _buf["UnitType"]; }
            { if(!_buf["Exp"].IsNumber) { throw new SerializationException(); }  Exp = _buf["Exp"]; }

            EndInit();
        }

        public static RogueKillExpEntryConfig DeserializeRogueKillExpEntryConfig(JSONNode _buf)
        {
            return new ET.RogueKillExpEntryConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 单位类型
        /// </summary>
        public readonly int UnitType;
        /// <summary>
        /// 击杀经验
        /// </summary>
        public readonly int Exp;

        public const int __ID__ = 548251152;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "UnitType:" + UnitType + ","
            + "Exp:" + Exp + ","
            + "}";
        }

        partial void EndRef();
    }

}

