
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class RogueLevelNumericEntryConfig : Luban.BeanBase
    {
        public RogueLevelNumericEntryConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Level = _buf.ReadInt();
            NumericType = _buf.ReadInt();
            Value = _buf.ReadLong();

            EndInit();
        }

        public static RogueLevelNumericEntryConfig DeserializeRogueLevelNumericEntryConfig(ByteBuf _buf)
        {
            return new ET.RogueLevelNumericEntryConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 等级
        /// </summary>
        public readonly int Level;
        /// <summary>
        /// 数值类型
        /// </summary>
        public readonly int NumericType;
        /// <summary>
        /// 增加值
        /// </summary>
        public readonly long Value;
    
        public const int __ID__ = -1885553296;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Level:" + Level + ","
            + "NumericType:" + NumericType + ","
            + "Value:" + Value + ","
            + "}";
        }

        partial void EndRef();
    }

}

