
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class RogueCardConfig : Luban.BeanBase
    {
        public RogueCardConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Desc = _buf.ReadString();
            ImagePath = _buf.ReadString();
            BTConfig = _buf.ReadString();
            Weight = _buf.ReadInt();
            Quality = _buf.ReadInt();
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ShowTags = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ShowTags[__index0] = __e0;}}
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);HideTags = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); HideTags[__index0] = __e0;}}

            EndInit();
        }

        public static RogueCardConfig DeserializeRogueCardConfig(ByteBuf _buf)
        {
            return new ET.RogueCardConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 肉鸽牌名称
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 肉鸽牌描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 图片路径
        /// </summary>
        public readonly string ImagePath;
        /// <summary>
        /// 效果配置(BTConfig，当前约定支持 buffId 或 buff:buffId)
        /// </summary>
        public readonly string BTConfig;
        /// <summary>
        /// 权重
        /// </summary>
        public readonly int Weight;
        /// <summary>
        /// 品质
        /// </summary>
        public readonly int Quality;
        /// <summary>
        /// 显示tags
        /// </summary>
        public readonly int[] ShowTags;
        /// <summary>
        /// 隐藏tags
        /// </summary>
        public readonly int[] HideTags;
    
        public const int __ID__ = 1843007629;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "ImagePath:" + ImagePath + ","
            + "BTConfig:" + BTConfig + ","
            + "Weight:" + Weight + ","
            + "Quality:" + Quality + ","
            + "ShowTags:" + Luban.StringUtil.CollectionToString(ShowTags) + ","
            + "HideTags:" + Luban.StringUtil.CollectionToString(HideTags) + ","
            + "}";
        }

        partial void EndRef();
    }

}

