
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class RogueLevelNumericEntryConfig : Luban.BeanBase
    {
        public RogueLevelNumericEntryConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["Level"].IsNumber) { throw new SerializationException(); }  Level = _buf["Level"]; }
            { if(!_buf["NumericType"].IsNumber) { throw new SerializationException(); }  NumericType = _buf["NumericType"]; }
            { if(!_buf["Value"].IsNumber) { throw new SerializationException(); }  Value = _buf["Value"]; }

            EndInit();
        }

        public static RogueLevelNumericEntryConfig DeserializeRogueLevelNumericEntryConfig(JSONNode _buf)
        {
            return new ET.RogueLevelNumericEntryConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 等级
        /// </summary>
        public readonly int Level;
        /// <summary>
        /// 数值类型
        /// </summary>
        public readonly int NumericType;
        /// <summary>
        /// 增加值
        /// </summary>
        public readonly long Value;

        public const int __ID__ = -1885553296;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Level:" + Level + ","
            + "NumericType:" + NumericType + ","
            + "Value:" + Value + ","
            + "}";
        }

        partial void EndRef();
    }

}

