
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class TacticalItemConfig : Luban.BeanBase
    {
        public TacticalItemConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            ItemConfigId = _buf.ReadInt();
            TacticalType = _buf.ReadInt();
            CastMode = _buf.ReadInt();
            BuffConfigId = _buf.ReadInt();
            Radius = _buf.ReadInt();
            MaxDistance = _buf.ReadInt();
            CooldownMs = _buf.ReadInt();
            IndicatorPath = _buf.ReadString();

            EndInit();
        }

        public static TacticalItemConfig DeserializeTacticalItemConfig(ByteBuf _buf)
        {
            return new ET.TacticalItemConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 物品配置ID
        /// </summary>
        public readonly int ItemConfigId;
        /// <summary>
        /// 战术类型
        /// </summary>
        public readonly int TacticalType;
        /// <summary>
        /// 释放模式
        /// </summary>
        public readonly int CastMode;
        /// <summary>
        /// Buff配置ID(BT入口)
        /// </summary>
        public readonly int BuffConfigId;
        /// <summary>
        /// 作用半径
        /// </summary>
        public readonly int Radius;
        /// <summary>
        /// 最大施法距离
        /// </summary>
        public readonly int MaxDistance;
        /// <summary>
        /// 冷却毫秒
        /// </summary>
        public readonly int CooldownMs;
        /// <summary>
        /// 指示器资源路径
        /// </summary>
        public readonly string IndicatorPath;
    
        public const int __ID__ = -874083401;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "ItemConfigId:" + ItemConfigId + ","
            + "TacticalType:" + TacticalType + ","
            + "CastMode:" + CastMode + ","
            + "BuffConfigId:" + BuffConfigId + ","
            + "Radius:" + Radius + ","
            + "MaxDistance:" + MaxDistance + ","
            + "CooldownMs:" + CooldownMs + ","
            + "IndicatorPath:" + IndicatorPath + ","
            + "}";
        }

        partial void EndRef();
    }

}

