
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class TagsConfig : Luban.BeanBase
    {
        public TagsConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["TagDes"].IsString) { throw new SerializationException(); }  TagDes = _buf["TagDes"]; }
            { if(!_buf["TagType"].IsNumber) { throw new SerializationException(); }  TagType = _buf["TagType"]; }
            { if(!_buf["ShowTagsName"].IsString) { throw new SerializationException(); }  ShowTagsName = _buf["ShowTagsName"]; }
            { if(!_buf["ShowTagsDesc"].IsString) { throw new SerializationException(); }  ShowTagsDesc = _buf["ShowTagsDesc"]; }
            { var __json0 = _buf["ShowTagsBuffId"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; ShowTagsBuffId = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ShowTagsBuffId[__index0++] = __v0; }   }
            { var __json0 = _buf["MatchValues"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; MatchValues = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  MatchValues[__index0++] = __v0; }   }

            EndInit();
        }

        public static TagsConfig DeserializeTagsConfig(JSONNode _buf)
        {
            return new ET.TagsConfig(_buf);
        }

        /// <summary>
        /// TagId
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string TagDes;
        /// <summary>
        /// 1：通用显示tag<br/>2：英雄tag<br/>3：枪械tag<br/>4：通用隐藏tag
        /// </summary>
        public readonly int TagType;
        /// <summary>
        /// 显示的tag名
        /// </summary>
        public readonly string ShowTagsName;
        /// <summary>
        /// 显示的tag描述
        /// </summary>
        public readonly string ShowTagsDesc;
        /// <summary>
        /// 显示的tag效果（1个的效果，2个的效果，3个的效果，4个的效果）
        /// </summary>
        public readonly int[] ShowTagsBuffId;
        /// <summary>
        /// 机读匹配值（英雄tag配HeroConfigId；枪械tag配WeaponTypeId）
        /// </summary>
        public readonly int[] MatchValues;

        public const int __ID__ = -295408774;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "TagDes:" + TagDes + ","
            + "TagType:" + TagType + ","
            + "ShowTagsName:" + ShowTagsName + ","
            + "ShowTagsDesc:" + ShowTagsDesc + ","
            + "ShowTagsBuffId:" + Luban.StringUtil.CollectionToString(ShowTagsBuffId) + ","
            + "MatchValues:" + Luban.StringUtil.CollectionToString(MatchValues) + ","
            + "}";
        }

        partial void EndRef();
    }

}

