
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class WeaponConfig : Luban.BeanBase
    {
        public WeaponConfig(JSONNode _buf) 
        {
            { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
            { if(!_buf["WeaponTypeId"].IsNumber) { throw new SerializationException(); }  WeaponTypeId = _buf["WeaponTypeId"]; }
            { if(!_buf["Damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["Damage"]; }
            { if(!_buf["AttackRange"].IsNumber) { throw new SerializationException(); }  AttackRange = _buf["AttackRange"]; }
            { if(!_buf["AttackIntervalMs"].IsNumber) { throw new SerializationException(); }  AttackIntervalMs = _buf["AttackIntervalMs"]; }
            { if(!_buf["MagazineSize"].IsNumber) { throw new SerializationException(); }  MagazineSize = _buf["MagazineSize"]; }
            { if(!_buf["ReloadTimeMs"].IsNumber) { throw new SerializationException(); }  ReloadTimeMs = _buf["ReloadTimeMs"]; }
            { if(!_buf["CanMoveWhileFire"].IsBoolean) { throw new SerializationException(); }  CanMoveWhileFire = _buf["CanMoveWhileFire"]; }
            { if(!_buf["FireLockTypeId"].IsNumber) { throw new SerializationException(); }  FireLockTypeId = _buf["FireLockTypeId"]; }
            { if(!_buf["BulletCount"].IsNumber) { throw new SerializationException(); }  BulletCount = _buf["BulletCount"]; }
            { if(!_buf["SpreadAngle"].IsNumber) { throw new SerializationException(); }  SpreadAngle = _buf["SpreadAngle"]; }
            { if(!_buf["Desc"].IsString) { throw new SerializationException(); }  Desc = _buf["Desc"]; }
            { if(!_buf["ProjectileEffect"].IsString) { throw new SerializationException(); }  ProjectileEffect = _buf["ProjectileEffect"]; }
            { if(!_buf["HitEffect"].IsString) { throw new SerializationException(); }  HitEffect = _buf["HitEffect"]; }
            { if(!_buf["WeaponPrefab"].IsString) { throw new SerializationException(); }  WeaponPrefab = _buf["WeaponPrefab"]; }
            { if(!_buf["CasterBindPointId"].IsNumber) { throw new SerializationException(); }  CasterBindPointId = _buf["CasterBindPointId"]; }
            { if(!_buf["TargetBindPointId"].IsNumber) { throw new SerializationException(); }  TargetBindPointId = _buf["TargetBindPointId"]; }
            { if(!_buf["WeaponBindPointId"].IsNumber) { throw new SerializationException(); }  WeaponBindPointId = _buf["WeaponBindPointId"]; }
            { if(!_buf["MuzzleBindPointId"].IsNumber) { throw new SerializationException(); }  MuzzleBindPointId = _buf["MuzzleBindPointId"]; }
            { if(!_buf["WeaponMuzzlePath"].IsString) { throw new SerializationException(); }  WeaponMuzzlePath = _buf["WeaponMuzzlePath"]; }
            { if(!_buf["WeaponLocalPositionX"].IsNumber) { throw new SerializationException(); }  WeaponLocalPositionX = _buf["WeaponLocalPositionX"]; }
            { if(!_buf["WeaponLocalPositionY"].IsNumber) { throw new SerializationException(); }  WeaponLocalPositionY = _buf["WeaponLocalPositionY"]; }
            { if(!_buf["WeaponLocalPositionZ"].IsNumber) { throw new SerializationException(); }  WeaponLocalPositionZ = _buf["WeaponLocalPositionZ"]; }
            { if(!_buf["WeaponLocalEulerX"].IsNumber) { throw new SerializationException(); }  WeaponLocalEulerX = _buf["WeaponLocalEulerX"]; }
            { if(!_buf["WeaponLocalEulerY"].IsNumber) { throw new SerializationException(); }  WeaponLocalEulerY = _buf["WeaponLocalEulerY"]; }
            { if(!_buf["WeaponLocalEulerZ"].IsNumber) { throw new SerializationException(); }  WeaponLocalEulerZ = _buf["WeaponLocalEulerZ"]; }
            { if(!_buf["WeaponLocalScale"].IsNumber) { throw new SerializationException(); }  WeaponLocalScale = _buf["WeaponLocalScale"]; }
            { if(!_buf["ProjectileSpeed"].IsNumber) { throw new SerializationException(); }  ProjectileSpeed = _buf["ProjectileSpeed"]; }
            { if(!_buf["ProjectileDurationMs"].IsNumber) { throw new SerializationException(); }  ProjectileDurationMs = _buf["ProjectileDurationMs"]; }
            { if(!_buf["HitEffectDurationMs"].IsNumber) { throw new SerializationException(); }  HitEffectDurationMs = _buf["HitEffectDurationMs"]; }
            { if(!_buf["FireAnimationType"].IsNumber) { throw new SerializationException(); }  FireAnimationType = _buf["FireAnimationType"]; }
            { if(!_buf["MuzzleFlashEffect"].IsString) { throw new SerializationException(); }  MuzzleFlashEffect = _buf["MuzzleFlashEffect"]; }
            { if(!_buf["MuzzleFlashDurationMs"].IsNumber) { throw new SerializationException(); }  MuzzleFlashDurationMs = _buf["MuzzleFlashDurationMs"]; }
            { if(!_buf["HitFlashDurationMs"].IsNumber) { throw new SerializationException(); }  HitFlashDurationMs = _buf["HitFlashDurationMs"]; }

            EndInit();
        }

        public static WeaponConfig DeserializeWeaponConfig(JSONNode _buf)
        {
            return new ET.WeaponConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 武器类型(1=霰弹枪,2=步枪1,3=步枪2,4=火箭炮)
        /// </summary>
        public readonly int WeaponTypeId;
        /// <summary>
        /// 伤害(单发)
        /// </summary>
        public readonly float Damage;
        /// <summary>
        /// 攻击范围(米)
        /// </summary>
        public readonly float AttackRange;
        /// <summary>
        /// 攻击间隔(毫秒)
        /// </summary>
        public readonly int AttackIntervalMs;
        /// <summary>
        /// 弹夹容量
        /// </summary>
        public readonly int MagazineSize;
        /// <summary>
        /// 换弹时间(毫秒)
        /// </summary>
        public readonly int ReloadTimeMs;
        /// <summary>
        /// 是否可边移动射击
        /// </summary>
        public readonly bool CanMoveWhileFire;
        /// <summary>
        /// 射击锁定类型(1=追踪,2=方向,3=位置)
        /// </summary>
        public readonly int FireLockTypeId;
        /// <summary>
        /// 单次子弹数
        /// </summary>
        public readonly int BulletCount;
        /// <summary>
        /// 散射角度(度)
        /// </summary>
        public readonly float SpreadAngle;
        /// <summary>
        /// 武器描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 投射物特效资源名
        /// </summary>
        public readonly string ProjectileEffect;
        /// <summary>
        /// 命中特效资源名
        /// </summary>
        public readonly string HitEffect;
        /// <summary>
        /// 武器模型资源名(留空表示暂无模型)
        /// </summary>
        public readonly string WeaponPrefab;
        /// <summary>
        /// 施法者默认发射绑定点
        /// </summary>
        public readonly int CasterBindPointId;
        /// <summary>
        /// 目标受击绑定点
        /// </summary>
        public readonly int TargetBindPointId;
        /// <summary>
        /// 武器挂载绑定点
        /// </summary>
        public readonly int WeaponBindPointId;
        /// <summary>
        /// 枪口回退绑定点
        /// </summary>
        public readonly int MuzzleBindPointId;
        /// <summary>
        /// 武器模型内枪口节点路径
        /// </summary>
        public readonly string WeaponMuzzlePath;
        /// <summary>
        /// 武器本地位置X
        /// </summary>
        public readonly float WeaponLocalPositionX;
        /// <summary>
        /// 武器本地位置Y
        /// </summary>
        public readonly float WeaponLocalPositionY;
        /// <summary>
        /// 武器本地位置Z
        /// </summary>
        public readonly float WeaponLocalPositionZ;
        /// <summary>
        /// 武器本地旋转X
        /// </summary>
        public readonly float WeaponLocalEulerX;
        /// <summary>
        /// 武器本地旋转Y
        /// </summary>
        public readonly float WeaponLocalEulerY;
        /// <summary>
        /// 武器本地旋转Z
        /// </summary>
        public readonly float WeaponLocalEulerZ;
        /// <summary>
        /// 武器本地缩放
        /// </summary>
        public readonly float WeaponLocalScale;
        /// <summary>
        /// 投射物速度
        /// </summary>
        public readonly float ProjectileSpeed;
        /// <summary>
        /// 投射物持续时间(毫秒)
        /// </summary>
        public readonly int ProjectileDurationMs;
        /// <summary>
        /// 命中特效持续时间(毫秒)
        /// </summary>
        public readonly int HitEffectDurationMs;
        /// <summary>
        /// 射击动画类型(1=单发,2=连发)
        /// </summary>
        public readonly int FireAnimationType;
        /// <summary>
        /// 枪口火焰特效Prefab名(空=不显示)
        /// </summary>
        public readonly string MuzzleFlashEffect;
        /// <summary>
        /// 枪口火焰持续时间(毫秒)
        /// </summary>
        public readonly int MuzzleFlashDurationMs;
        /// <summary>
        /// 命中闪光时长(毫秒)
        /// </summary>
        public readonly int HitFlashDurationMs;

        public const int __ID__ = 940013437;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "WeaponTypeId:" + WeaponTypeId + ","
            + "Damage:" + Damage + ","
            + "AttackRange:" + AttackRange + ","
            + "AttackIntervalMs:" + AttackIntervalMs + ","
            + "MagazineSize:" + MagazineSize + ","
            + "ReloadTimeMs:" + ReloadTimeMs + ","
            + "CanMoveWhileFire:" + CanMoveWhileFire + ","
            + "FireLockTypeId:" + FireLockTypeId + ","
            + "BulletCount:" + BulletCount + ","
            + "SpreadAngle:" + SpreadAngle + ","
            + "Desc:" + Desc + ","
            + "ProjectileEffect:" + ProjectileEffect + ","
            + "HitEffect:" + HitEffect + ","
            + "WeaponPrefab:" + WeaponPrefab + ","
            + "CasterBindPointId:" + CasterBindPointId + ","
            + "TargetBindPointId:" + TargetBindPointId + ","
            + "WeaponBindPointId:" + WeaponBindPointId + ","
            + "MuzzleBindPointId:" + MuzzleBindPointId + ","
            + "WeaponMuzzlePath:" + WeaponMuzzlePath + ","
            + "WeaponLocalPositionX:" + WeaponLocalPositionX + ","
            + "WeaponLocalPositionY:" + WeaponLocalPositionY + ","
            + "WeaponLocalPositionZ:" + WeaponLocalPositionZ + ","
            + "WeaponLocalEulerX:" + WeaponLocalEulerX + ","
            + "WeaponLocalEulerY:" + WeaponLocalEulerY + ","
            + "WeaponLocalEulerZ:" + WeaponLocalEulerZ + ","
            + "WeaponLocalScale:" + WeaponLocalScale + ","
            + "ProjectileSpeed:" + ProjectileSpeed + ","
            + "ProjectileDurationMs:" + ProjectileDurationMs + ","
            + "HitEffectDurationMs:" + HitEffectDurationMs + ","
            + "FireAnimationType:" + FireAnimationType + ","
            + "MuzzleFlashEffect:" + MuzzleFlashEffect + ","
            + "MuzzleFlashDurationMs:" + MuzzleFlashDurationMs + ","
            + "HitFlashDurationMs:" + HitFlashDurationMs + ","
            + "}";
        }

        partial void EndRef();
    }

}

