
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class WeaponConfig : Luban.BeanBase
    {
        public WeaponConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            WeaponTypeId = _buf.ReadInt();
            Damage = _buf.ReadFloat();
            AttackRange = _buf.ReadFloat();
            AttackIntervalMs = _buf.ReadInt();
            MagazineSize = _buf.ReadInt();
            ReloadTimeMs = _buf.ReadInt();
            CanMoveWhileFire = _buf.ReadBool();
            FireLockTypeId = _buf.ReadInt();
            BulletCount = _buf.ReadInt();
            SpreadAngle = _buf.ReadFloat();
            Desc = _buf.ReadString();

            EndInit();
        }

        public static WeaponConfig DeserializeWeaponConfig(ByteBuf _buf)
        {
            return new ET.WeaponConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 武器类型(1=霰弹枪,2=步枪1,3=步枪2,4=火箭炮)
        /// </summary>
        public readonly int WeaponTypeId;
        /// <summary>
        /// 伤害(单发)
        /// </summary>
        public readonly float Damage;
        /// <summary>
        /// 攻击范围(米)
        /// </summary>
        public readonly float AttackRange;
        /// <summary>
        /// 攻击间隔(毫秒)
        /// </summary>
        public readonly int AttackIntervalMs;
        /// <summary>
        /// 弹夹容量
        /// </summary>
        public readonly int MagazineSize;
        /// <summary>
        /// 换弹时间(毫秒)
        /// </summary>
        public readonly int ReloadTimeMs;
        /// <summary>
        /// 是否可边移动射击
        /// </summary>
        public readonly bool CanMoveWhileFire;
        /// <summary>
        /// 射击锁定类型(1=追踪,2=方向,3=位置)
        /// </summary>
        public readonly int FireLockTypeId;
        /// <summary>
        /// 单次子弹数
        /// </summary>
        public readonly int BulletCount;
        /// <summary>
        /// 散射角度(度)
        /// </summary>
        public readonly float SpreadAngle;
        /// <summary>
        /// 武器描述
        /// </summary>
        public readonly string Desc;
    
        public const int __ID__ = 940013437;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "WeaponTypeId:" + WeaponTypeId + ","
            + "Damage:" + Damage + ","
            + "AttackRange:" + AttackRange + ","
            + "AttackIntervalMs:" + AttackIntervalMs + ","
            + "MagazineSize:" + MagazineSize + ","
            + "ReloadTimeMs:" + ReloadTimeMs + ","
            + "CanMoveWhileFire:" + CanMoveWhileFire + ","
            + "FireLockTypeId:" + FireLockTypeId + ","
            + "BulletCount:" + BulletCount + ","
            + "SpreadAngle:" + SpreadAngle + ","
            + "Desc:" + Desc + ","
            + "}";
        }

        partial void EndRef();
    }

}

