
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class HomeMainCityTaskConfig : Luban.BeanBase
    {
        public HomeMainCityTaskConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            TaskGroupId = _buf.ReadInt();
            TaskType = _buf.ReadInt();
            Param1 = _buf.ReadInt();
            Param2 = _buf.ReadInt();
            Title = _buf.ReadString();
            Desc = _buf.ReadString();
            SortOrder = _buf.ReadInt();

            EndInit();
        }

        public static HomeMainCityTaskConfig DeserializeHomeMainCityTaskConfig(ByteBuf _buf)
        {
            return new ET.HomeMainCityTaskConfig(_buf);
        }

        public readonly int Id;
        public readonly int TaskGroupId;
        public readonly int TaskType;
        public readonly int Param1;
        public readonly int Param2;
        public readonly string Title;
        public readonly string Desc;
        public readonly int SortOrder;
    
        public const int __ID__ = -364305783;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "TaskGroupId:" + TaskGroupId + ","
            + "TaskType:" + TaskType + ","
            + "Param1:" + Param1 + ","
            + "Param2:" + Param2 + ","
            + "Title:" + Title + ","
            + "Desc:" + Desc + ","
            + "SortOrder:" + SortOrder + ","
            + "}";
        }

        partial void EndRef();
    }

}

