
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class HomeSlotConfig : Luban.BeanBase
    {
        public HomeSlotConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["SlotType"].IsNumber) { throw new SerializationException(); }  SlotType = _buf["SlotType"]; }
            { if(!_buf["SceneAnchorKey"].IsString) { throw new SerializationException(); }  SceneAnchorKey = _buf["SceneAnchorKey"]; }
            { if(!_buf["UnlockMainCityLevel"].IsNumber) { throw new SerializationException(); }  UnlockMainCityLevel = _buf["UnlockMainCityLevel"]; }
            { var __json0 = _buf["CanBuildTypes"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; CanBuildTypes = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  CanBuildTypes[__index0++] = __v0; }   }
            { if(!_buf["SortOrder"].IsNumber) { throw new SerializationException(); }  SortOrder = _buf["SortOrder"]; }

            EndInit();
        }

        public static HomeSlotConfig DeserializeHomeSlotConfig(JSONNode _buf)
        {
            return new ET.HomeSlotConfig(_buf);
        }

        public readonly int Id;
        public readonly int SlotType;
        public readonly string SceneAnchorKey;
        public readonly int UnlockMainCityLevel;
        public readonly int[] CanBuildTypes;
        public readonly int SortOrder;

        public const int __ID__ = 426340446;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "SlotType:" + SlotType + ","
            + "SceneAnchorKey:" + SceneAnchorKey + ","
            + "UnlockMainCityLevel:" + UnlockMainCityLevel + ","
            + "CanBuildTypes:" + Luban.StringUtil.CollectionToString(CanBuildTypes) + ","
            + "SortOrder:" + SortOrder + ","
            + "}";
        }

        partial void EndRef();
    }

}

