
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson.Serialization.Options;

namespace ET
{

    [ConfigProcess(ConfigType.Luban)]
    public partial class HomeMainCityTaskConfigCategory : Singleton<HomeMainCityTaskConfigCategory>, IConfig
    {
        [BsonElement]
        [BsonDictionaryOptions(DictionaryRepresentation.ArrayOfArrays)]
        private readonly Dictionary<int, ET.HomeMainCityTaskConfig> _dataMap;
        private readonly List<ET.HomeMainCityTaskConfig> _dataList;
        
        public HomeMainCityTaskConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ET.HomeMainCityTaskConfig>();
            _dataList = new List<ET.HomeMainCityTaskConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                ET.HomeMainCityTaskConfig _v;
                _v = global::ET.HomeMainCityTaskConfig.DeserializeHomeMainCityTaskConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, ET.HomeMainCityTaskConfig> GetAll() => _dataMap;
        public Dictionary<int, ET.HomeMainCityTaskConfig> DataMap => _dataMap;
        public List<ET.HomeMainCityTaskConfig> DataList => _dataList;

        public ET.HomeMainCityTaskConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public ET.HomeMainCityTaskConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            throw new System.Exception($"not found config: {this.GetType().FullName}, key: {key}");
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

