
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class ItemConfig : Luban.BeanBase
    {
        public ItemConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Desc = _buf.ReadString();
            Type = _buf.ReadInt();
            MaxStack = _buf.ReadInt();
            Icon = _buf.ReadString();
            Quality = _buf.ReadInt();
            UseType = _buf.ReadInt();
            Level = _buf.ReadInt();

            EndInit();
        }

        public static ItemConfig DeserializeItemConfig(ByteBuf _buf)
        {
            return new ET.ItemConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 类型
        /// </summary>
        public readonly int Type;
        /// <summary>
        /// 最大堆叠
        /// </summary>
        public readonly int MaxStack;
        /// <summary>
        /// 图标
        /// </summary>
        public readonly string Icon;
        /// <summary>
        /// 品质
        /// </summary>
        public readonly int Quality;
        /// <summary>
        /// 使用类型
        /// </summary>
        public readonly int UseType;
        /// <summary>
        /// 等级
        /// </summary>
        public readonly int Level;
    
        public const int __ID__ = 1663635188;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "Type:" + Type + ","
            + "MaxStack:" + MaxStack + ","
            + "Icon:" + Icon + ","
            + "Quality:" + Quality + ","
            + "UseType:" + UseType + ","
            + "Level:" + Level + ","
            + "}";
        }

        partial void EndRef();
    }

}

