
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class MinimapConstConfig : Luban.BeanBase
    {
        public MinimapConstConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["Key"].IsString) { throw new SerializationException(); }  Key = _buf["Key"]; }
            { if(!_buf["FloatValue"].IsNumber) { throw new SerializationException(); }  FloatValue = _buf["FloatValue"]; }
            { if(!_buf["StringValue"].IsString) { throw new SerializationException(); }  StringValue = _buf["StringValue"]; }

            EndInit();
        }

        public static MinimapConstConfig DeserializeMinimapConstConfig(JSONNode _buf)
        {
            return new ET.MinimapConstConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 配置Key
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// 浮点值
        /// </summary>
        public readonly float FloatValue;
        /// <summary>
        /// 字符串值
        /// </summary>
        public readonly string StringValue;

        public const int __ID__ = -181358241;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Key:" + Key + ","
            + "FloatValue:" + FloatValue + ","
            + "StringValue:" + StringValue + ","
            + "}";
        }

        partial void EndRef();
    }

}

