
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class MinimapConstConfig : Luban.BeanBase
    {
        public MinimapConstConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Key = _buf.ReadString();
            FloatValue = _buf.ReadFloat();
            StringValue = _buf.ReadString();

            EndInit();
        }

        public static MinimapConstConfig DeserializeMinimapConstConfig(ByteBuf _buf)
        {
            return new ET.MinimapConstConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 配置Key
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// 浮点值
        /// </summary>
        public readonly float FloatValue;
        /// <summary>
        /// 字符串值
        /// </summary>
        public readonly string StringValue;
    
        public const int __ID__ = -181358241;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Key:" + Key + ","
            + "FloatValue:" + FloatValue + ","
            + "StringValue:" + StringValue + ","
            + "}";
        }

        partial void EndRef();
    }

}

