
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class NavmeshGuardConfig : Luban.BeanBase
    {
        public NavmeshGuardConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["MovementProjectHalfExtentXZ"].IsNumber) { throw new SerializationException(); }  MovementProjectHalfExtentXZ = _buf["MovementProjectHalfExtentXZ"]; }
            { if(!_buf["MovementProjectHalfExtentY"].IsNumber) { throw new SerializationException(); }  MovementProjectHalfExtentY = _buf["MovementProjectHalfExtentY"]; }
            { if(!_buf["MovementProjectHalfExtentByRadius"].IsNumber) { throw new SerializationException(); }  MovementProjectHalfExtentByRadius = _buf["MovementProjectHalfExtentByRadius"]; }
            { if(!_buf["MovementRejectDistance"].IsNumber) { throw new SerializationException(); }  MovementRejectDistance = _buf["MovementRejectDistance"]; }
            { if(!_buf["MovementRejectDistanceByRadius"].IsNumber) { throw new SerializationException(); }  MovementRejectDistanceByRadius = _buf["MovementRejectDistanceByRadius"]; }
            { if(!_buf["FindNearestRejectDistance"].IsNumber) { throw new SerializationException(); }  FindNearestRejectDistance = _buf["FindNearestRejectDistance"]; }
            { if(!_buf["FindNearestRejectDistanceByRadius"].IsNumber) { throw new SerializationException(); }  FindNearestRejectDistanceByRadius = _buf["FindNearestRejectDistanceByRadius"]; }
            { if(!_buf["MinUnitRadius"].IsNumber) { throw new SerializationException(); }  MinUnitRadius = _buf["MinUnitRadius"]; }

            EndInit();
        }

        public static NavmeshGuardConfig DeserializeNavmeshGuardConfig(JSONNode _buf)
        {
            return new ET.NavmeshGuardConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 移动投影半径XZ
        /// </summary>
        public readonly float MovementProjectHalfExtentXZ;
        /// <summary>
        /// 移动投影半径Y
        /// </summary>
        public readonly float MovementProjectHalfExtentY;
        /// <summary>
        /// 移动投影半径按角色系数
        /// </summary>
        public readonly float MovementProjectHalfExtentByRadius;
        /// <summary>
        /// 摇杆偏差阈值
        /// </summary>
        public readonly float MovementRejectDistance;
        /// <summary>
        /// 摇杆偏差阈值按角色系数
        /// </summary>
        public readonly float MovementRejectDistanceByRadius;
        /// <summary>
        /// 寻路吸附偏差阈值
        /// </summary>
        public readonly float FindNearestRejectDistance;
        /// <summary>
        /// 寻路吸附偏差阈值按角色系数
        /// </summary>
        public readonly float FindNearestRejectDistanceByRadius;
        /// <summary>
        /// 最小角色半径
        /// </summary>
        public readonly float MinUnitRadius;

        public const int __ID__ = -256367018;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "MovementProjectHalfExtentXZ:" + MovementProjectHalfExtentXZ + ","
            + "MovementProjectHalfExtentY:" + MovementProjectHalfExtentY + ","
            + "MovementProjectHalfExtentByRadius:" + MovementProjectHalfExtentByRadius + ","
            + "MovementRejectDistance:" + MovementRejectDistance + ","
            + "MovementRejectDistanceByRadius:" + MovementRejectDistanceByRadius + ","
            + "FindNearestRejectDistance:" + FindNearestRejectDistance + ","
            + "FindNearestRejectDistanceByRadius:" + FindNearestRejectDistanceByRadius + ","
            + "MinUnitRadius:" + MinUnitRadius + ","
            + "}";
        }

        partial void EndRef();
    }

}

