
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson.Serialization.Options;

namespace ET
{

    [ConfigProcess(ConfigType.Luban)]
    public partial class RogueGlobalConfigCategory : Singleton<RogueGlobalConfigCategory>, IConfig
    {

        private readonly ET.RogueGlobalConfig _data;

        public ET.RogueGlobalConfig Data => _data;

        public RogueGlobalConfigCategory(ByteBuf _buf)
        {
            int n = _buf.ReadSize();
            if (n != 1) throw new SerializationException("table mode=one, but size != 1");
            _data = global::ET.RogueGlobalConfig.DeserializeRogueGlobalConfig(_buf);
			EndInit();
        }


        /// <summary>
        /// ID
        /// </summary>
        public int Id => _data.Id;
        /// <summary>
        /// 默认击杀经验
        /// </summary>
        public int DefaultKillExp => _data.DefaultKillExp;
        /// <summary>
        /// 选牌数量
        /// </summary>
        public int ChoiceOptionCount => _data.ChoiceOptionCount;
        /// <summary>
        /// 品质1随机权重
        /// </summary>
        public int QualityRandom1 => _data.QualityRandom1;
        /// <summary>
        /// 品质2随机权重
        /// </summary>
        public int QualityRandom2 => _data.QualityRandom2;
        /// <summary>
        /// 品质3随机权重
        /// </summary>
        public int QualityRandom3 => _data.QualityRandom3;
        /// <summary>
        /// 保险槽起始索引
        /// </summary>
        public int SafeSlotStart => _data.SafeSlotStart;
        /// <summary>
        /// 保险槽数量
        /// </summary>
        public int SafeSlotCount => _data.SafeSlotCount;
        /// <summary>
        /// 尸体盒交互距离
        /// </summary>
        public float CorpseInteractRange => _data.CorpseInteractRange;
        /// <summary>
        /// 尸体盒交互按钮文案ID
        /// </summary>
        public int CorpseButtonTextId => _data.CorpseButtonTextId;
        /// <summary>
        /// 默认怪物尸体盒UnitConfigId
        /// </summary>
        public int DefaultMonsterCorpseLootBoxUnitConfigId => _data.DefaultMonsterCorpseLootBoxUnitConfigId;
        
        public void ResolveRef()
        {
            _data.ResolveRef();
            EndRef();
        }

        partial void EndRef();
    }

}

