
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class RogueLevelEntryConfig : Luban.BeanBase
    {
        public RogueLevelEntryConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Level = _buf.ReadInt();
            NeedExp = _buf.ReadInt();
            TriggerChoice = _buf.ReadBool();

            EndInit();
        }

        public static RogueLevelEntryConfig DeserializeRogueLevelEntryConfig(ByteBuf _buf)
        {
            return new ET.RogueLevelEntryConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 等级
        /// </summary>
        public readonly int Level;
        /// <summary>
        /// 升级所需经验
        /// </summary>
        public readonly int NeedExp;
        /// <summary>
        /// 是否触发选牌
        /// </summary>
        public readonly bool TriggerChoice;
    
        public const int __ID__ = 902872587;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Level:" + Level + ","
            + "NeedExp:" + NeedExp + ","
            + "TriggerChoice:" + TriggerChoice + ","
            + "}";
        }

        partial void EndRef();
    }

}

