
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson.Serialization.Options;

namespace ET
{

    [ConfigProcess(ConfigType.Luban)]
    public partial class RogueGlobalConfigCategory : Singleton<RogueGlobalConfigCategory>, IConfig
    {

        private readonly ET.RogueGlobalConfig _data;

        public ET.RogueGlobalConfig Data => _data;

        public RogueGlobalConfigCategory(ByteBuf _buf)
        {
            int n = _buf.ReadSize();
            if (n != 1) throw new SerializationException("table mode=one, but size != 1");
            _data = global::ET.RogueGlobalConfig.DeserializeRogueGlobalConfig(_buf);
			EndInit();
        }


        /// <summary>
        /// ID
        /// </summary>
        public int Id => _data.Id;
        /// <summary>
        /// 默认击杀经验
        /// </summary>
        public int DefaultKillExp => _data.DefaultKillExp;
        /// <summary>
        /// 选牌数量
        /// </summary>
        public int ChoiceOptionCount => _data.ChoiceOptionCount;
        
        public void ResolveRef()
        {
            _data.ResolveRef();
            EndRef();
        }

        partial void EndRef();
    }

}

