
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class EquipmentConfig : Luban.BeanBase
    {
        public EquipmentConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            EquipSlot = _buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);KV = new System.Collections.Generic.Dictionary<int, long>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); long _v0;  _v0 = _buf.ReadLong();     KV.Add(_k0, _v0);}}

            EndInit();
        }

        public static EquipmentConfig DeserializeEquipmentConfig(ByteBuf _buf)
        {
            return new ET.EquipmentConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 装备部位
        /// </summary>
        public readonly int EquipSlot;
        /// <summary>
        /// 速度Base
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<int, long> KV;
    
        public const int __ID__ = -904342767;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "EquipSlot:" + EquipSlot + ","
            + "KV:" + Luban.StringUtil.CollectionToString(KV) + ","
            + "}";
        }

        partial void EndRef();
    }

}

