
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class HeroDisplayConfig : Luban.BeanBase
    {
        public HeroDisplayConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["ModelResName"].IsString) { throw new SerializationException(); }  ModelResName = _buf["ModelResName"]; }
            { if(!_buf["CameraName"].IsString) { throw new SerializationException(); }  CameraName = _buf["CameraName"]; }
            { if(!_buf["PropertyDesc"].IsString) { throw new SerializationException(); }  PropertyDesc = _buf["PropertyDesc"]; }
            { if(!_buf["SkillDesc"].IsString) { throw new SerializationException(); }  SkillDesc = _buf["SkillDesc"]; }

            EndInit();
        }

        public static HeroDisplayConfig DeserializeHeroDisplayConfig(JSONNode _buf)
        {
            return new ET.HeroDisplayConfig(_buf);
        }

        /// <summary>
        /// 英雄配置Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 3D模型资源名
        /// </summary>
        public readonly string ModelResName;
        /// <summary>
        /// 模型内观察相机节点名(可空)
        /// </summary>
        public readonly string CameraName;
        /// <summary>
        /// 属性描述
        /// </summary>
        public readonly string PropertyDesc;
        /// <summary>
        /// 技能描述
        /// </summary>
        public readonly string SkillDesc;

        public const int __ID__ = -2044735189;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ModelResName:" + ModelResName + ","
            + "CameraName:" + CameraName + ","
            + "PropertyDesc:" + PropertyDesc + ","
            + "SkillDesc:" + SkillDesc + ","
            + "}";
        }

        partial void EndRef();
    }

}

