
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class HeroConfig : Luban.BeanBase
    {
        public HeroConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
            { if(!_buf["UnitConfigId"].IsNumber) { throw new SerializationException(); }  UnitConfigId = _buf["UnitConfigId"]; }
            { if(!_buf["SkillConfigId"].IsNumber) { throw new SerializationException(); }  SkillConfigId = _buf["SkillConfigId"]; }
            { if(!_buf["PassiveBuffId"].IsNumber) { throw new SerializationException(); }  PassiveBuffId = _buf["PassiveBuffId"]; }

            EndInit();
        }

        public static HeroConfig DeserializeHeroConfig(JSONNode _buf)
        {
            return new ET.HeroConfig(_buf);
        }

        public readonly int Id;
        public readonly string Name;
        public readonly int UnitConfigId;
        public readonly int SkillConfigId;
        public readonly int PassiveBuffId;

        public const int __ID__ = 1863899803;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "UnitConfigId:" + UnitConfigId + ","
            + "SkillConfigId:" + SkillConfigId + ","
            + "PassiveBuffId:" + PassiveBuffId + ","
            + "}";
        }

        partial void EndRef();
    }

}

