
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class HeroConfig : Luban.BeanBase
    {
        public HeroConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            UnitConfigId = _buf.ReadInt();
            SkillConfigId = _buf.ReadInt();
            PassiveBuffId = _buf.ReadInt();
            HealRange = _buf.ReadFloat();
            HealIntervalMs = _buf.ReadInt();
            HealAmount = _buf.ReadFloat();

            EndInit();
        }

        public static HeroConfig DeserializeHeroConfig(ByteBuf _buf)
        {
            return new ET.HeroConfig(_buf);
        }

        public readonly int Id;
        public readonly string Name;
        public readonly int UnitConfigId;
        public readonly int SkillConfigId;
        public readonly int PassiveBuffId;
        public readonly float HealRange;
        public readonly int HealIntervalMs;
        public readonly float HealAmount;
    
        public const int __ID__ = 1863899803;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "UnitConfigId:" + UnitConfigId + ","
            + "SkillConfigId:" + SkillConfigId + ","
            + "PassiveBuffId:" + PassiveBuffId + ","
            + "HealRange:" + HealRange + ","
            + "HealIntervalMs:" + HealIntervalMs + ","
            + "HealAmount:" + HealAmount + ","
            + "}";
        }

        partial void EndRef();
    }

}


