
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class HeroDisplayConfig : Luban.BeanBase
    {
        public HeroDisplayConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            ModelResName = _buf.ReadString();
            CameraName = _buf.ReadString();
            PropertyDesc = _buf.ReadString();
            SkillDesc = _buf.ReadString();

            EndInit();
        }

        public static HeroDisplayConfig DeserializeHeroDisplayConfig(ByteBuf _buf)
        {
            return new ET.HeroDisplayConfig(_buf);
        }

        /// <summary>
        /// 英雄配置Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 3D模型资源名
        /// </summary>
        public readonly string ModelResName;
        /// <summary>
        /// 模型内观察相机节点名(可空)
        /// </summary>
        public readonly string CameraName;
        /// <summary>
        /// 属性描述
        /// </summary>
        public readonly string PropertyDesc;
        /// <summary>
        /// 技能描述
        /// </summary>
        public readonly string SkillDesc;
    
        public const int __ID__ = -2044735189;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ModelResName:" + ModelResName + ","
            + "CameraName:" + CameraName + ","
            + "PropertyDesc:" + PropertyDesc + ","
            + "SkillDesc:" + SkillDesc + ","
            + "}";
        }

        partial void EndRef();
    }

}

