
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class HomeSlotConfig : Luban.BeanBase
    {
        public HomeSlotConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            SlotType = _buf.ReadInt();
            SceneAnchorKey = _buf.ReadString();
            UnlockMainCityLevel = _buf.ReadInt();
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);CanBuildTypes = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); CanBuildTypes[__index0] = __e0;}}
            SortOrder = _buf.ReadInt();

            EndInit();
        }

        public static HomeSlotConfig DeserializeHomeSlotConfig(ByteBuf _buf)
        {
            return new ET.HomeSlotConfig(_buf);
        }

        public readonly int Id;
        public readonly int SlotType;
        public readonly string SceneAnchorKey;
        public readonly int UnlockMainCityLevel;
        public readonly int[] CanBuildTypes;
        public readonly int SortOrder;
    
        public const int __ID__ = 426340446;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "SlotType:" + SlotType + ","
            + "SceneAnchorKey:" + SceneAnchorKey + ","
            + "UnlockMainCityLevel:" + UnlockMainCityLevel + ","
            + "CanBuildTypes:" + Luban.StringUtil.CollectionToString(CanBuildTypes) + ","
            + "SortOrder:" + SortOrder + ","
            + "}";
        }

        partial void EndRef();
    }

}

