
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class HomeMainCityLevelConfig : Luban.BeanBase
    {
        public HomeMainCityLevelConfig(JSONNode _buf) 
        {
            { if(!_buf["Level"].IsNumber) { throw new SerializationException(); }  Level = _buf["Level"]; }
            { if(!_buf["UpgradeGoldCost"].IsNumber) { throw new SerializationException(); }  UpgradeGoldCost = _buf["UpgradeGoldCost"]; }
            { if(!_buf["UnlockSlotCount"].IsNumber) { throw new SerializationException(); }  UnlockSlotCount = _buf["UnlockSlotCount"]; }
            { if(!_buf["OtherBuildingMaxLevel"].IsNumber) { throw new SerializationException(); }  OtherBuildingMaxLevel = _buf["OtherBuildingMaxLevel"]; }
            { if(!_buf["TaskGroupId"].IsNumber) { throw new SerializationException(); }  TaskGroupId = _buf["TaskGroupId"]; }
            { if(!_buf["PreviewText"].IsString) { throw new SerializationException(); }  PreviewText = _buf["PreviewText"]; }

            EndInit();
        }

        public static HomeMainCityLevelConfig DeserializeHomeMainCityLevelConfig(JSONNode _buf)
        {
            return new ET.HomeMainCityLevelConfig(_buf);
        }

        public readonly int Level;
        public readonly int UpgradeGoldCost;
        public readonly int UnlockSlotCount;
        public readonly int OtherBuildingMaxLevel;
        public readonly int TaskGroupId;
        public readonly string PreviewText;

        public const int __ID__ = 71143108;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Level:" + Level + ","
            + "UpgradeGoldCost:" + UpgradeGoldCost + ","
            + "UnlockSlotCount:" + UnlockSlotCount + ","
            + "OtherBuildingMaxLevel:" + OtherBuildingMaxLevel + ","
            + "TaskGroupId:" + TaskGroupId + ","
            + "PreviewText:" + PreviewText + ","
            + "}";
        }

        partial void EndRef();
    }

}

