
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class HomeMainCityLevelConfig : Luban.BeanBase
    {
        public HomeMainCityLevelConfig(ByteBuf _buf) 
        {
            Level = _buf.ReadInt();
            UpgradeGoldCost = _buf.ReadInt();
            UnlockSlotCount = _buf.ReadInt();
            OtherBuildingMaxLevel = _buf.ReadInt();
            TaskGroupId = _buf.ReadInt();
            PreviewText = _buf.ReadString();

            EndInit();
        }

        public static HomeMainCityLevelConfig DeserializeHomeMainCityLevelConfig(ByteBuf _buf)
        {
            return new ET.HomeMainCityLevelConfig(_buf);
        }

        public readonly int Level;
        public readonly int UpgradeGoldCost;
        public readonly int UnlockSlotCount;
        public readonly int OtherBuildingMaxLevel;
        public readonly int TaskGroupId;
        public readonly string PreviewText;
    
        public const int __ID__ = 71143108;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Level:" + Level + ","
            + "UpgradeGoldCost:" + UpgradeGoldCost + ","
            + "UnlockSlotCount:" + UnlockSlotCount + ","
            + "OtherBuildingMaxLevel:" + OtherBuildingMaxLevel + ","
            + "TaskGroupId:" + TaskGroupId + ","
            + "PreviewText:" + PreviewText + ","
            + "}";
        }

        partial void EndRef();
    }

}

