
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class HomeBuildingLevelConfig : Luban.BeanBase
    {
        public HomeBuildingLevelConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["BuildingConfigId"].IsNumber) { throw new SerializationException(); }  BuildingConfigId = _buf["BuildingConfigId"]; }
            { if(!_buf["Level"].IsNumber) { throw new SerializationException(); }  Level = _buf["Level"]; }
            { if(!_buf["UpgradeGoldCost"].IsNumber) { throw new SerializationException(); }  UpgradeGoldCost = _buf["UpgradeGoldCost"]; }
            { if(!_buf["CapacityValue1"].IsNumber) { throw new SerializationException(); }  CapacityValue1 = _buf["CapacityValue1"]; }
            { if(!_buf["CapacityValue2"].IsNumber) { throw new SerializationException(); }  CapacityValue2 = _buf["CapacityValue2"]; }
            { if(!_buf["OutputValue"].IsNumber) { throw new SerializationException(); }  OutputValue = _buf["OutputValue"]; }
            { if(!_buf["ExtraParams"].IsString) { throw new SerializationException(); }  ExtraParams = _buf["ExtraParams"]; }

            EndInit();
        }

        public static HomeBuildingLevelConfig DeserializeHomeBuildingLevelConfig(JSONNode _buf)
        {
            return new ET.HomeBuildingLevelConfig(_buf);
        }

        public readonly int Id;
        public readonly int BuildingConfigId;
        public readonly int Level;
        public readonly int UpgradeGoldCost;
        public readonly int CapacityValue1;
        public readonly int CapacityValue2;
        public readonly int OutputValue;
        public readonly string ExtraParams;

        public const int __ID__ = 971388116;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "BuildingConfigId:" + BuildingConfigId + ","
            + "Level:" + Level + ","
            + "UpgradeGoldCost:" + UpgradeGoldCost + ","
            + "CapacityValue1:" + CapacityValue1 + ","
            + "CapacityValue2:" + CapacityValue2 + ","
            + "OutputValue:" + OutputValue + ","
            + "ExtraParams:" + ExtraParams + ","
            + "}";
        }

        partial void EndRef();
    }

}

