
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class HomeBuildingConfig : Luban.BeanBase
    {
        public HomeBuildingConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["BuildingType"].IsNumber) { throw new SerializationException(); }  BuildingType = _buf["BuildingType"]; }
            { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
            { if(!_buf["SceneVisualKey"].IsString) { throw new SerializationException(); }  SceneVisualKey = _buf["SceneVisualKey"]; }
            { if(!_buf["CanRepeat"].IsBoolean) { throw new SerializationException(); }  CanRepeat = _buf["CanRepeat"]; }
            { if(!_buf["MaxCount"].IsNumber) { throw new SerializationException(); }  MaxCount = _buf["MaxCount"]; }
            { if(!_buf["SortOrder"].IsNumber) { throw new SerializationException(); }  SortOrder = _buf["SortOrder"]; }
            { if(!_buf["DefaultUnlock"].IsBoolean) { throw new SerializationException(); }  DefaultUnlock = _buf["DefaultUnlock"]; }
            { if(!_buf["DefaultSlotType"].IsNumber) { throw new SerializationException(); }  DefaultSlotType = _buf["DefaultSlotType"]; }
            { if(!_buf["BuildGoldCost"].IsNumber) { throw new SerializationException(); }  BuildGoldCost = _buf["BuildGoldCost"]; }

            EndInit();
        }

        public static HomeBuildingConfig DeserializeHomeBuildingConfig(JSONNode _buf)
        {
            return new ET.HomeBuildingConfig(_buf);
        }

        public readonly int Id;
        public readonly int BuildingType;
        public readonly string Name;
        public readonly string SceneVisualKey;
        public readonly bool CanRepeat;
        public readonly int MaxCount;
        public readonly int SortOrder;
        public readonly bool DefaultUnlock;
        public readonly int DefaultSlotType;
        public readonly int BuildGoldCost;

        public const int __ID__ = -226571884;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "BuildingType:" + BuildingType + ","
            + "Name:" + Name + ","
            + "SceneVisualKey:" + SceneVisualKey + ","
            + "CanRepeat:" + CanRepeat + ","
            + "MaxCount:" + MaxCount + ","
            + "SortOrder:" + SortOrder + ","
            + "DefaultUnlock:" + DefaultUnlock + ","
            + "DefaultSlotType:" + DefaultSlotType + ","
            + "BuildGoldCost:" + BuildGoldCost + ","
            + "}";
        }

        partial void EndRef();
    }

}

