
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class HomeBuildingConfig : Luban.BeanBase
    {
        public HomeBuildingConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            BuildingType = _buf.ReadInt();
            Name = _buf.ReadString();
            SceneVisualKey = _buf.ReadString();
            CanRepeat = _buf.ReadBool();
            MaxCount = _buf.ReadInt();
            SortOrder = _buf.ReadInt();
            DefaultUnlock = _buf.ReadBool();
            DefaultSlotType = _buf.ReadInt();
            BuildGoldCost = _buf.ReadInt();

            EndInit();
        }

        public static HomeBuildingConfig DeserializeHomeBuildingConfig(ByteBuf _buf)
        {
            return new ET.HomeBuildingConfig(_buf);
        }

        public readonly int Id;
        public readonly int BuildingType;
        public readonly string Name;
        public readonly string SceneVisualKey;
        public readonly bool CanRepeat;
        public readonly int MaxCount;
        public readonly int SortOrder;
        public readonly bool DefaultUnlock;
        public readonly int DefaultSlotType;
        public readonly int BuildGoldCost;
    
        public const int __ID__ = -226571884;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "BuildingType:" + BuildingType + ","
            + "Name:" + Name + ","
            + "SceneVisualKey:" + SceneVisualKey + ","
            + "CanRepeat:" + CanRepeat + ","
            + "MaxCount:" + MaxCount + ","
            + "SortOrder:" + SortOrder + ","
            + "DefaultUnlock:" + DefaultUnlock + ","
            + "DefaultSlotType:" + DefaultSlotType + ","
            + "BuildGoldCost:" + BuildGoldCost + ","
            + "}";
        }

        partial void EndRef();
    }

}

