
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class ItemConfig : Luban.BeanBase
    {
        public ItemConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Type = _buf.ReadInt();
            MaxStack = _buf.ReadInt();
            Quality = _buf.ReadInt();
            UseType = _buf.ReadInt();
            Level = _buf.ReadInt();
            GridWidth = _buf.ReadInt();
            GridHeight = _buf.ReadInt();
            LoadoutShopVisible = _buf.ReadBool();
            LoadoutShopCategory = _buf.ReadInt();
            LoadoutBuyPrice = _buf.ReadInt();
            CanEquipMainWeapon = _buf.ReadBool();
            CanEquipSubWeapon = _buf.ReadBool();
            CanEquipArmor = _buf.ReadBool();
            CanEquipBackpack = _buf.ReadBool();
            IsBackpack = _buf.ReadBool();
            BackpackWidth = _buf.ReadInt();
            BackpackHeight = _buf.ReadInt();

            EndInit();
        }

        public static ItemConfig DeserializeItemConfig(ByteBuf _buf)
        {
            return new ET.ItemConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 类型
        /// </summary>
        public readonly int Type;
        /// <summary>
        /// 最大堆叠
        /// </summary>
        public readonly int MaxStack;
        /// <summary>
        /// 品质
        /// </summary>
        public readonly int Quality;
        /// <summary>
        /// 使用类型
        /// </summary>
        public readonly int UseType;
        /// <summary>
        /// 等级
        /// </summary>
        public readonly int Level;
        /// <summary>
        /// 格子宽
        /// </summary>
        public readonly int GridWidth;
        /// <summary>
        /// 格子高
        /// </summary>
        public readonly int GridHeight;
        /// <summary>
        /// 起装商店可见
        /// </summary>
        public readonly bool LoadoutShopVisible;
        /// <summary>
        /// 起装商店分类
        /// </summary>
        public readonly int LoadoutShopCategory;
        /// <summary>
        /// 起装购买价
        /// </summary>
        public readonly int LoadoutBuyPrice;
        /// <summary>
        /// 可装备主武器槽
        /// </summary>
        public readonly bool CanEquipMainWeapon;
        /// <summary>
        /// 可装备副武器槽
        /// </summary>
        public readonly bool CanEquipSubWeapon;
        /// <summary>
        /// 可装备护甲槽
        /// </summary>
        public readonly bool CanEquipArmor;
        /// <summary>
        /// 可装备背包槽
        /// </summary>
        public readonly bool CanEquipBackpack;
        /// <summary>
        /// 是否背包
        /// </summary>
        public readonly bool IsBackpack;
        /// <summary>
        /// 背包宽
        /// </summary>
        public readonly int BackpackWidth;
        /// <summary>
        /// 背包高
        /// </summary>
        public readonly int BackpackHeight;
    
        public const int __ID__ = 1663635188;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Type:" + Type + ","
            + "MaxStack:" + MaxStack + ","
            + "Quality:" + Quality + ","
            + "UseType:" + UseType + ","
            + "Level:" + Level + ","
            + "GridWidth:" + GridWidth + ","
            + "GridHeight:" + GridHeight + ","
            + "LoadoutShopVisible:" + LoadoutShopVisible + ","
            + "LoadoutShopCategory:" + LoadoutShopCategory + ","
            + "LoadoutBuyPrice:" + LoadoutBuyPrice + ","
            + "CanEquipMainWeapon:" + CanEquipMainWeapon + ","
            + "CanEquipSubWeapon:" + CanEquipSubWeapon + ","
            + "CanEquipArmor:" + CanEquipArmor + ","
            + "CanEquipBackpack:" + CanEquipBackpack + ","
            + "IsBackpack:" + IsBackpack + ","
            + "BackpackWidth:" + BackpackWidth + ","
            + "BackpackHeight:" + BackpackHeight + ","
            + "}";
        }

        partial void EndRef();
    }

}

