
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class ItemConfig : Luban.BeanBase
    {
        public ItemConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
            { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
            { if(!_buf["MaxStack"].IsNumber) { throw new SerializationException(); }  MaxStack = _buf["MaxStack"]; }
            { if(!_buf["Quality"].IsNumber) { throw new SerializationException(); }  Quality = _buf["Quality"]; }
            { if(!_buf["UseType"].IsNumber) { throw new SerializationException(); }  UseType = _buf["UseType"]; }
            { if(!_buf["Level"].IsNumber) { throw new SerializationException(); }  Level = _buf["Level"]; }
            { if(!_buf["GridWidth"].IsNumber) { throw new SerializationException(); }  GridWidth = _buf["GridWidth"]; }
            { if(!_buf["GridHeight"].IsNumber) { throw new SerializationException(); }  GridHeight = _buf["GridHeight"]; }
            { if(!_buf["LoadoutShopVisible"].IsBoolean) { throw new SerializationException(); }  LoadoutShopVisible = _buf["LoadoutShopVisible"]; }
            { if(!_buf["LoadoutShopCategory"].IsNumber) { throw new SerializationException(); }  LoadoutShopCategory = _buf["LoadoutShopCategory"]; }
            { if(!_buf["LoadoutBuyPrice"].IsNumber) { throw new SerializationException(); }  LoadoutBuyPrice = _buf["LoadoutBuyPrice"]; }
            { if(!_buf["CanEquipMainWeapon"].IsBoolean) { throw new SerializationException(); }  CanEquipMainWeapon = _buf["CanEquipMainWeapon"]; }
            { if(!_buf["CanEquipSubWeapon"].IsBoolean) { throw new SerializationException(); }  CanEquipSubWeapon = _buf["CanEquipSubWeapon"]; }
            { if(!_buf["CanEquipArmor"].IsBoolean) { throw new SerializationException(); }  CanEquipArmor = _buf["CanEquipArmor"]; }
            { if(!_buf["CanEquipBackpack"].IsBoolean) { throw new SerializationException(); }  CanEquipBackpack = _buf["CanEquipBackpack"]; }
            { if(!_buf["IsBackpack"].IsBoolean) { throw new SerializationException(); }  IsBackpack = _buf["IsBackpack"]; }
            { if(!_buf["BackpackWidth"].IsNumber) { throw new SerializationException(); }  BackpackWidth = _buf["BackpackWidth"]; }
            { if(!_buf["BackpackHeight"].IsNumber) { throw new SerializationException(); }  BackpackHeight = _buf["BackpackHeight"]; }

            EndInit();
        }

        public static ItemConfig DeserializeItemConfig(JSONNode _buf)
        {
            return new ET.ItemConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 类型
        /// </summary>
        public readonly int Type;
        /// <summary>
        /// 最大堆叠
        /// </summary>
        public readonly int MaxStack;
        /// <summary>
        /// 品质
        /// </summary>
        public readonly int Quality;
        /// <summary>
        /// 使用类型
        /// </summary>
        public readonly int UseType;
        /// <summary>
        /// 等级
        /// </summary>
        public readonly int Level;
        /// <summary>
        /// 格子宽
        /// </summary>
        public readonly int GridWidth;
        /// <summary>
        /// 格子高
        /// </summary>
        public readonly int GridHeight;
        /// <summary>
        /// 起装商店可见
        /// </summary>
        public readonly bool LoadoutShopVisible;
        /// <summary>
        /// 起装商店分类
        /// </summary>
        public readonly int LoadoutShopCategory;
        /// <summary>
        /// 起装购买价
        /// </summary>
        public readonly int LoadoutBuyPrice;
        /// <summary>
        /// 可装备主武器槽
        /// </summary>
        public readonly bool CanEquipMainWeapon;
        /// <summary>
        /// 可装备副武器槽
        /// </summary>
        public readonly bool CanEquipSubWeapon;
        /// <summary>
        /// 可装备护甲槽
        /// </summary>
        public readonly bool CanEquipArmor;
        /// <summary>
        /// 可装备背包槽
        /// </summary>
        public readonly bool CanEquipBackpack;
        /// <summary>
        /// 是否背包
        /// </summary>
        public readonly bool IsBackpack;
        /// <summary>
        /// 背包宽
        /// </summary>
        public readonly int BackpackWidth;
        /// <summary>
        /// 背包高
        /// </summary>
        public readonly int BackpackHeight;

        public const int __ID__ = 1663635188;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Type:" + Type + ","
            + "MaxStack:" + MaxStack + ","
            + "Quality:" + Quality + ","
            + "UseType:" + UseType + ","
            + "Level:" + Level + ","
            + "GridWidth:" + GridWidth + ","
            + "GridHeight:" + GridHeight + ","
            + "LoadoutShopVisible:" + LoadoutShopVisible + ","
            + "LoadoutShopCategory:" + LoadoutShopCategory + ","
            + "LoadoutBuyPrice:" + LoadoutBuyPrice + ","
            + "CanEquipMainWeapon:" + CanEquipMainWeapon + ","
            + "CanEquipSubWeapon:" + CanEquipSubWeapon + ","
            + "CanEquipArmor:" + CanEquipArmor + ","
            + "CanEquipBackpack:" + CanEquipBackpack + ","
            + "IsBackpack:" + IsBackpack + ","
            + "BackpackWidth:" + BackpackWidth + ","
            + "BackpackHeight:" + BackpackHeight + ","
            + "}";
        }

        partial void EndRef();
    }

}

