
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class MatchRobotConfig : Luban.BeanBase
    {
        public MatchRobotConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["MapName"].IsString) { throw new SerializationException(); }  MapName = _buf["MapName"]; }
            { if(!_buf["GameMode"].IsNumber) { throw new SerializationException(); }  GameMode = _buf["GameMode"]; }
            { if(!_buf["AIBuffConfigId"].IsNumber) { throw new SerializationException(); }  AIBuffConfigId = _buf["AIBuffConfigId"]; }
            { if(!_buf["HeroConfigIds"].IsString) { throw new SerializationException(); }  HeroConfigIds = _buf["HeroConfigIds"]; }
            { if(!_buf["HeroWeights"].IsString) { throw new SerializationException(); }  HeroWeights = _buf["HeroWeights"]; }
            { if(!_buf["MainWeaponConfigIds"].IsString) { throw new SerializationException(); }  MainWeaponConfigIds = _buf["MainWeaponConfigIds"]; }
            { if(!_buf["MainWeaponWeights"].IsString) { throw new SerializationException(); }  MainWeaponWeights = _buf["MainWeaponWeights"]; }
            { if(!_buf["AutoChooseDelayMinMs"].IsNumber) { throw new SerializationException(); }  AutoChooseDelayMinMs = _buf["AutoChooseDelayMinMs"]; }
            { if(!_buf["AutoChooseDelayMaxMs"].IsNumber) { throw new SerializationException(); }  AutoChooseDelayMaxMs = _buf["AutoChooseDelayMaxMs"]; }

            EndInit();
        }

        public static MatchRobotConfig DeserializeMatchRobotConfig(JSONNode _buf)
        {
            return new ET.MatchRobotConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 地图名（空=通用）
        /// </summary>
        public readonly string MapName;
        /// <summary>
        /// 游戏模式（0=通用）
        /// </summary>
        public readonly int GameMode;
        /// <summary>
        /// 机器人AI BuffId
        /// </summary>
        public readonly int AIBuffConfigId;
        /// <summary>
        /// 可随机英雄配置（|分隔）
        /// </summary>
        public readonly string HeroConfigIds;
        /// <summary>
        /// 英雄权重（|分隔）
        /// </summary>
        public readonly string HeroWeights;
        /// <summary>
        /// 可随机主武器配置（|分隔）
        /// </summary>
        public readonly string MainWeaponConfigIds;
        /// <summary>
        /// 主武器权重（|分隔）
        /// </summary>
        public readonly string MainWeaponWeights;
        /// <summary>
        /// 自动选项最小延迟毫秒
        /// </summary>
        public readonly int AutoChooseDelayMinMs;
        /// <summary>
        /// 自动选项最大延迟毫秒
        /// </summary>
        public readonly int AutoChooseDelayMaxMs;

        public const int __ID__ = -493943098;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "MapName:" + MapName + ","
            + "GameMode:" + GameMode + ","
            + "AIBuffConfigId:" + AIBuffConfigId + ","
            + "HeroConfigIds:" + HeroConfigIds + ","
            + "HeroWeights:" + HeroWeights + ","
            + "MainWeaponConfigIds:" + MainWeaponConfigIds + ","
            + "MainWeaponWeights:" + MainWeaponWeights + ","
            + "AutoChooseDelayMinMs:" + AutoChooseDelayMinMs + ","
            + "AutoChooseDelayMaxMs:" + AutoChooseDelayMaxMs + ","
            + "}";
        }

        partial void EndRef();
    }

}

