
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class MonsterCorpseLootConfig : Luban.BeanBase
    {
        public MonsterCorpseLootConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            MapName = _buf.ReadString();
            MonsterUnitConfigId = _buf.ReadInt();
            LootBoxUnitConfigId = _buf.ReadInt();
            LootTable = _buf.ReadString();
            DropCountMin = _buf.ReadInt();
            DropCountMax = _buf.ReadInt();
            AllowRepeat = _buf.ReadBool();

            EndInit();
        }

        public static MonsterCorpseLootConfig DeserializeMonsterCorpseLootConfig(ByteBuf _buf)
        {
            return new ET.MonsterCorpseLootConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 地图名
        /// </summary>
        public readonly string MapName;
        /// <summary>
        /// 怪物UnitConfigId
        /// </summary>
        public readonly int MonsterUnitConfigId;
        /// <summary>
        /// 盒子UnitConfigId
        /// </summary>
        public readonly int LootBoxUnitConfigId;
        /// <summary>
        /// 掉落表
        /// </summary>
        public readonly string LootTable;
        /// <summary>
        /// 最少掉落次数
        /// </summary>
        public readonly int DropCountMin;
        /// <summary>
        /// 最多掉落次数
        /// </summary>
        public readonly int DropCountMax;
        /// <summary>
        /// 允许重复
        /// </summary>
        public readonly bool AllowRepeat;
    
        public const int __ID__ = 1509002305;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "MapName:" + MapName + ","
            + "MonsterUnitConfigId:" + MonsterUnitConfigId + ","
            + "LootBoxUnitConfigId:" + LootBoxUnitConfigId + ","
            + "LootTable:" + LootTable + ","
            + "DropCountMin:" + DropCountMin + ","
            + "DropCountMax:" + DropCountMax + ","
            + "AllowRepeat:" + AllowRepeat + ","
            + "}";
        }

        partial void EndRef();
    }

}

