
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class RogueKillExpEntryConfig : Luban.BeanBase
    {
        public RogueKillExpEntryConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            UnitType = _buf.ReadInt();
            Exp = _buf.ReadInt();

            EndInit();
        }

        public static RogueKillExpEntryConfig DeserializeRogueKillExpEntryConfig(ByteBuf _buf)
        {
            return new ET.RogueKillExpEntryConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 单位类型
        /// </summary>
        public readonly int UnitType;
        /// <summary>
        /// 击杀经验
        /// </summary>
        public readonly int Exp;
    
        public const int __ID__ = 548251152;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "UnitType:" + UnitType + ","
            + "Exp:" + Exp + ","
            + "}";
        }

        partial void EndRef();
    }

}

