
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class RogueCardConfig : Luban.BeanBase
    {
        public RogueCardConfig(JSONNode _buf) 
        {
            { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
            { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
            { if(!_buf["Desc"].IsString) { throw new SerializationException(); }  Desc = _buf["Desc"]; }
            { if(!_buf["ImagePath"].IsString) { throw new SerializationException(); }  ImagePath = _buf["ImagePath"]; }
            { if(!_buf["BTConfig"].IsString) { throw new SerializationException(); }  BTConfig = _buf["BTConfig"]; }
            { if(!_buf["Weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["Weight"]; }
            { if(!_buf["Quality"].IsNumber) { throw new SerializationException(); }  Quality = _buf["Quality"]; }
            { var __json0 = _buf["ShowTags"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; ShowTags = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ShowTags[__index0++] = __v0; }   }
            { var __json0 = _buf["HideTags"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; HideTags = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  HideTags[__index0++] = __v0; }   }

            EndInit();
        }

        public static RogueCardConfig DeserializeRogueCardConfig(JSONNode _buf)
        {
            return new ET.RogueCardConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 肉鸽牌名称
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 肉鸽牌描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 图片路径
        /// </summary>
        public readonly string ImagePath;
        /// <summary>
        /// 效果配置(BTConfig，当前约定支持 buffId 或 buff:buffId)
        /// </summary>
        public readonly string BTConfig;
        /// <summary>
        /// 权重
        /// </summary>
        public readonly int Weight;
        /// <summary>
        /// 品质
        /// </summary>
        public readonly int Quality;
        /// <summary>
        /// 显示tags
        /// </summary>
        public readonly int[] ShowTags;
        /// <summary>
        /// 隐藏tags
        /// </summary>
        public readonly int[] HideTags;

        public const int __ID__ = 1843007629;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "ImagePath:" + ImagePath + ","
            + "BTConfig:" + BTConfig + ","
            + "Weight:" + Weight + ","
            + "Quality:" + Quality + ","
            + "ShowTags:" + Luban.StringUtil.CollectionToString(ShowTags) + ","
            + "HideTags:" + Luban.StringUtil.CollectionToString(HideTags) + ","
            + "}";
        }

        partial void EndRef();
    }

}

