
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class RogueLevelEntryConfig : Luban.BeanBase
    {
        public RogueLevelEntryConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["Level"].IsNumber) { throw new SerializationException(); }  Level = _buf["Level"]; }
            { if(!_buf["NeedExp"].IsNumber) { throw new SerializationException(); }  NeedExp = _buf["NeedExp"]; }
            { if(!_buf["TriggerChoice"].IsBoolean) { throw new SerializationException(); }  TriggerChoice = _buf["TriggerChoice"]; }

            EndInit();
        }

        public static RogueLevelEntryConfig DeserializeRogueLevelEntryConfig(JSONNode _buf)
        {
            return new ET.RogueLevelEntryConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 等级
        /// </summary>
        public readonly int Level;
        /// <summary>
        /// 升级所需经验
        /// </summary>
        public readonly int NeedExp;
        /// <summary>
        /// 是否触发选牌
        /// </summary>
        public readonly bool TriggerChoice;

        public const int __ID__ = 902872587;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Level:" + Level + ","
            + "NeedExp:" + NeedExp + ","
            + "TriggerChoice:" + TriggerChoice + ","
            + "}";
        }

        partial void EndRef();
    }

}

