
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class RogueGlobalConfig : Luban.BeanBase
    {
        public RogueGlobalConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            DefaultKillExp = _buf.ReadInt();
            ChoiceOptionCount = _buf.ReadInt();

            EndInit();
        }

        public static RogueGlobalConfig DeserializeRogueGlobalConfig(ByteBuf _buf)
        {
            return new ET.RogueGlobalConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 默认击杀经验
        /// </summary>
        public readonly int DefaultKillExp;
        /// <summary>
        /// 选牌数量
        /// </summary>
        public readonly int ChoiceOptionCount;
    
        public const int __ID__ = 597591072;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "DefaultKillExp:" + DefaultKillExp + ","
            + "ChoiceOptionCount:" + ChoiceOptionCount + ","
            + "}";
        }

        partial void EndRef();
    }

}

