
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class RogueGlobalConfig : Luban.BeanBase
    {
        public RogueGlobalConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            DefaultKillExp = _buf.ReadInt();
            ChoiceOptionCount = _buf.ReadInt();
            QualityRandom1 = _buf.ReadInt();
            QualityRandom2 = _buf.ReadInt();
            QualityRandom3 = _buf.ReadInt();
            SafeSlotStart = _buf.ReadInt();
            SafeSlotCount = _buf.ReadInt();
            CorpseInteractRange = _buf.ReadFloat();
            CorpseButtonTextId = _buf.ReadInt();
            DefaultMonsterCorpseLootBoxUnitConfigId = _buf.ReadInt();
            AutoSecureMinValuePerGrid = _buf.ReadInt();

            EndInit();
        }

        public static RogueGlobalConfig DeserializeRogueGlobalConfig(ByteBuf _buf)
        {
            return new ET.RogueGlobalConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 默认击杀经验
        /// </summary>
        public readonly int DefaultKillExp;
        /// <summary>
        /// 选牌数量
        /// </summary>
        public readonly int ChoiceOptionCount;
        /// <summary>
        /// 品质1随机权重
        /// </summary>
        public readonly int QualityRandom1;
        /// <summary>
        /// 品质2随机权重
        /// </summary>
        public readonly int QualityRandom2;
        /// <summary>
        /// 品质3随机权重
        /// </summary>
        public readonly int QualityRandom3;
        /// <summary>
        /// 保险槽起始索引
        /// </summary>
        public readonly int SafeSlotStart;
        /// <summary>
        /// 保险槽数量
        /// </summary>
        public readonly int SafeSlotCount;
        /// <summary>
        /// 尸体盒交互距离
        /// </summary>
        public readonly float CorpseInteractRange;
        /// <summary>
        /// 尸体盒交互按钮文案ID
        /// </summary>
        public readonly int CorpseButtonTextId;
        /// <summary>
        /// 默认怪物尸体盒UnitConfigId
        /// </summary>
        public readonly int DefaultMonsterCorpseLootBoxUnitConfigId;
        /// <summary>
        /// 自动拾取进安全格的单格最小价值
        /// </summary>
        public readonly int AutoSecureMinValuePerGrid;
    
        public const int __ID__ = 597591072;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "DefaultKillExp:" + DefaultKillExp + ","
            + "ChoiceOptionCount:" + ChoiceOptionCount + ","
            + "QualityRandom1:" + QualityRandom1 + ","
            + "QualityRandom2:" + QualityRandom2 + ","
            + "QualityRandom3:" + QualityRandom3 + ","
            + "SafeSlotStart:" + SafeSlotStart + ","
            + "SafeSlotCount:" + SafeSlotCount + ","
            + "CorpseInteractRange:" + CorpseInteractRange + ","
            + "CorpseButtonTextId:" + CorpseButtonTextId + ","
            + "DefaultMonsterCorpseLootBoxUnitConfigId:" + DefaultMonsterCorpseLootBoxUnitConfigId + ","
            + "AutoSecureMinValuePerGrid:" + AutoSecureMinValuePerGrid + ","
            + "}";
        }

        partial void EndRef();
    }

}

