
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class TacticalItemConfig : Luban.BeanBase
    {
        public TacticalItemConfig(JSONNode _buf) 
        {
            { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
            { if(!_buf["ItemConfigId"].IsNumber) { throw new SerializationException(); }  ItemConfigId = _buf["ItemConfigId"]; }
            { if(!_buf["TacticalType"].IsNumber) { throw new SerializationException(); }  TacticalType = _buf["TacticalType"]; }
            { if(!_buf["CastMode"].IsNumber) { throw new SerializationException(); }  CastMode = _buf["CastMode"]; }
            { if(!_buf["BuffConfigId"].IsNumber) { throw new SerializationException(); }  BuffConfigId = _buf["BuffConfigId"]; }
            { if(!_buf["Radius"].IsNumber) { throw new SerializationException(); }  Radius = _buf["Radius"]; }
            { if(!_buf["MaxDistance"].IsNumber) { throw new SerializationException(); }  MaxDistance = _buf["MaxDistance"]; }
            { if(!_buf["CooldownMs"].IsNumber) { throw new SerializationException(); }  CooldownMs = _buf["CooldownMs"]; }
            { if(!_buf["IndicatorPath"].IsString) { throw new SerializationException(); }  IndicatorPath = _buf["IndicatorPath"]; }

            EndInit();
        }

        public static TacticalItemConfig DeserializeTacticalItemConfig(JSONNode _buf)
        {
            return new ET.TacticalItemConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 物品配置ID
        /// </summary>
        public readonly int ItemConfigId;
        /// <summary>
        /// 战术类型
        /// </summary>
        public readonly int TacticalType;
        /// <summary>
        /// 释放模式
        /// </summary>
        public readonly int CastMode;
        /// <summary>
        /// Buff配置ID(BT入口)
        /// </summary>
        public readonly int BuffConfigId;
        /// <summary>
        /// 作用半径
        /// </summary>
        public readonly int Radius;
        /// <summary>
        /// 最大施法距离
        /// </summary>
        public readonly int MaxDistance;
        /// <summary>
        /// 冷却毫秒
        /// </summary>
        public readonly int CooldownMs;
        /// <summary>
        /// 指示器资源路径
        /// </summary>
        public readonly string IndicatorPath;

        public const int __ID__ = -874083401;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "ItemConfigId:" + ItemConfigId + ","
            + "TacticalType:" + TacticalType + ","
            + "CastMode:" + CastMode + ","
            + "BuffConfigId:" + BuffConfigId + ","
            + "Radius:" + Radius + ","
            + "MaxDistance:" + MaxDistance + ","
            + "CooldownMs:" + CooldownMs + ","
            + "IndicatorPath:" + IndicatorPath + ","
            + "}";
        }

        partial void EndRef();
    }

}

