
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class TagsConfig : Luban.BeanBase
    {
        public TagsConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            TagDes = _buf.ReadString();
            TagType = _buf.ReadInt();
            ShowTagsName = _buf.ReadString();
            ShowTagsDesc = _buf.ReadString();
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ShowTagsBuffId = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ShowTagsBuffId[__index0] = __e0;}}
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);MatchValues = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); MatchValues[__index0] = __e0;}}

            EndInit();
        }

        public static TagsConfig DeserializeTagsConfig(ByteBuf _buf)
        {
            return new ET.TagsConfig(_buf);
        }

        /// <summary>
        /// TagId
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string TagDes;
        /// <summary>
        /// 1：通用显示tag<br/>2：英雄tag<br/>3：枪械tag<br/>4：通用隐藏tag
        /// </summary>
        public readonly int TagType;
        /// <summary>
        /// 显示的tag名
        /// </summary>
        public readonly string ShowTagsName;
        /// <summary>
        /// 显示的tag描述
        /// </summary>
        public readonly string ShowTagsDesc;
        /// <summary>
        /// 显示的tag效果（1个的效果，2个的效果，3个的效果，4个的效果）
        /// </summary>
        public readonly int[] ShowTagsBuffId;
        /// <summary>
        /// 机读匹配值（英雄tag配HeroConfigId；枪械tag配WeaponTypeId）
        /// </summary>
        public readonly int[] MatchValues;
    
        public const int __ID__ = -295408774;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "TagDes:" + TagDes + ","
            + "TagType:" + TagType + ","
            + "ShowTagsName:" + ShowTagsName + ","
            + "ShowTagsDesc:" + ShowTagsDesc + ","
            + "ShowTagsBuffId:" + Luban.StringUtil.CollectionToString(ShowTagsBuffId) + ","
            + "MatchValues:" + Luban.StringUtil.CollectionToString(MatchValues) + ","
            + "}";
        }

        partial void EndRef();
    }

}

