
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson.Serialization.Options;
using SimpleJSON;

namespace ET
{

    /// <summary>
    /// 武器战斗配置表
    /// </summary>
    [ConfigProcess(ConfigType.Json)]
    public partial class WeaponConfigCategory : Singleton<WeaponConfigCategory>, IConfig
    {
        [BsonElement]
        [BsonDictionaryOptions(DictionaryRepresentation.ArrayOfArrays)]
        private readonly Dictionary<int, ET.WeaponConfig> _dataMap;
        private readonly List<ET.WeaponConfig> _dataList;

        public WeaponConfigCategory(JSONNode _buf)
        {
            _dataMap = new Dictionary<int, ET.WeaponConfig>();
            _dataList = new List<ET.WeaponConfig>();

            foreach(JSONNode _ele in _buf.Children)
            {
                ET.WeaponConfig _v;
                { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::ET.WeaponConfig.DeserializeWeaponConfig(_ele);  }
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, ET.WeaponConfig> GetAll() => _dataMap;
        public Dictionary<int, ET.WeaponConfig> DataMap => _dataMap;
        public List<ET.WeaponConfig> DataList => _dataList;

        public ET.WeaponConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public ET.WeaponConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            throw new System.Exception($"not found config: {this.GetType().FullName}, key: {key}");
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

