
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class WeaponConfig : Luban.BeanBase
    {
        public WeaponConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            WeaponTypeId = _buf.ReadInt();
            Damage = _buf.ReadFloat();
            AttackRange = _buf.ReadFloat();
            AttackIntervalMs = _buf.ReadInt();
            MagazineSize = _buf.ReadInt();
            ReloadTimeMs = _buf.ReadInt();
            CanMoveWhileFire = _buf.ReadBool();
            FireLockTypeId = _buf.ReadInt();
            BulletCount = _buf.ReadInt();
            SpreadAngle = _buf.ReadFloat();
            Desc = _buf.ReadString();
            ProjectileEffect = _buf.ReadString();
            HitEffect = _buf.ReadString();
            WeaponPrefab = _buf.ReadString();
            CasterBindPointId = _buf.ReadInt();
            TargetBindPointId = _buf.ReadInt();
            WeaponBindPointId = _buf.ReadInt();
            MuzzleBindPointId = _buf.ReadInt();
            WeaponMuzzlePath = _buf.ReadString();
            WeaponLocalPositionX = _buf.ReadFloat();
            WeaponLocalPositionY = _buf.ReadFloat();
            WeaponLocalPositionZ = _buf.ReadFloat();
            WeaponLocalEulerX = _buf.ReadFloat();
            WeaponLocalEulerY = _buf.ReadFloat();
            WeaponLocalEulerZ = _buf.ReadFloat();
            WeaponLocalScale = _buf.ReadFloat();
            ProjectileSpeed = _buf.ReadFloat();
            ProjectileDurationMs = _buf.ReadInt();
            HitEffectDurationMs = _buf.ReadInt();

            EndInit();
        }

        public static WeaponConfig DeserializeWeaponConfig(ByteBuf _buf)
        {
            return new ET.WeaponConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 武器类型(1=霰弹枪,2=步枪1,3=步枪2,4=火箭炮)
        /// </summary>
        public readonly int WeaponTypeId;
        /// <summary>
        /// 伤害(单发)
        /// </summary>
        public readonly float Damage;
        /// <summary>
        /// 攻击范围(米)
        /// </summary>
        public readonly float AttackRange;
        /// <summary>
        /// 攻击间隔(毫秒)
        /// </summary>
        public readonly int AttackIntervalMs;
        /// <summary>
        /// 弹夹容量
        /// </summary>
        public readonly int MagazineSize;
        /// <summary>
        /// 换弹时间(毫秒)
        /// </summary>
        public readonly int ReloadTimeMs;
        /// <summary>
        /// 是否可边移动射击
        /// </summary>
        public readonly bool CanMoveWhileFire;
        /// <summary>
        /// 射击锁定类型(1=追踪,2=方向,3=位置)
        /// </summary>
        public readonly int FireLockTypeId;
        /// <summary>
        /// 单次子弹数
        /// </summary>
        public readonly int BulletCount;
        /// <summary>
        /// 散射角度(度)
        /// </summary>
        public readonly float SpreadAngle;
        /// <summary>
        /// 武器描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 投射物特效资源名
        /// </summary>
        public readonly string ProjectileEffect;
        /// <summary>
        /// 命中特效资源名
        /// </summary>
        public readonly string HitEffect;
        /// <summary>
        /// 武器模型资源名(留空表示暂无模型)
        /// </summary>
        public readonly string WeaponPrefab;
        /// <summary>
        /// 施法者默认发射绑定点
        /// </summary>
        public readonly int CasterBindPointId;
        /// <summary>
        /// 目标受击绑定点
        /// </summary>
        public readonly int TargetBindPointId;
        /// <summary>
        /// 武器挂载绑定点
        /// </summary>
        public readonly int WeaponBindPointId;
        /// <summary>
        /// 枪口回退绑定点
        /// </summary>
        public readonly int MuzzleBindPointId;
        /// <summary>
        /// 武器模型内枪口节点路径
        /// </summary>
        public readonly string WeaponMuzzlePath;
        /// <summary>
        /// 武器本地位置X
        /// </summary>
        public readonly float WeaponLocalPositionX;
        /// <summary>
        /// 武器本地位置Y
        /// </summary>
        public readonly float WeaponLocalPositionY;
        /// <summary>
        /// 武器本地位置Z
        /// </summary>
        public readonly float WeaponLocalPositionZ;
        /// <summary>
        /// 武器本地旋转X
        /// </summary>
        public readonly float WeaponLocalEulerX;
        /// <summary>
        /// 武器本地旋转Y
        /// </summary>
        public readonly float WeaponLocalEulerY;
        /// <summary>
        /// 武器本地旋转Z
        /// </summary>
        public readonly float WeaponLocalEulerZ;
        /// <summary>
        /// 武器本地缩放
        /// </summary>
        public readonly float WeaponLocalScale;
        /// <summary>
        /// 投射物速度
        /// </summary>
        public readonly float ProjectileSpeed;
        /// <summary>
        /// 投射物持续时间(毫秒)
        /// </summary>
        public readonly int ProjectileDurationMs;
        /// <summary>
        /// 命中特效持续时间(毫秒)
        /// </summary>
        public readonly int HitEffectDurationMs;
    
        public const int __ID__ = 940013437;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "WeaponTypeId:" + WeaponTypeId + ","
            + "Damage:" + Damage + ","
            + "AttackRange:" + AttackRange + ","
            + "AttackIntervalMs:" + AttackIntervalMs + ","
            + "MagazineSize:" + MagazineSize + ","
            + "ReloadTimeMs:" + ReloadTimeMs + ","
            + "CanMoveWhileFire:" + CanMoveWhileFire + ","
            + "FireLockTypeId:" + FireLockTypeId + ","
            + "BulletCount:" + BulletCount + ","
            + "SpreadAngle:" + SpreadAngle + ","
            + "Desc:" + Desc + ","
            + "ProjectileEffect:" + ProjectileEffect + ","
            + "HitEffect:" + HitEffect + ","
            + "WeaponPrefab:" + WeaponPrefab + ","
            + "CasterBindPointId:" + CasterBindPointId + ","
            + "TargetBindPointId:" + TargetBindPointId + ","
            + "WeaponBindPointId:" + WeaponBindPointId + ","
            + "MuzzleBindPointId:" + MuzzleBindPointId + ","
            + "WeaponMuzzlePath:" + WeaponMuzzlePath + ","
            + "WeaponLocalPositionX:" + WeaponLocalPositionX + ","
            + "WeaponLocalPositionY:" + WeaponLocalPositionY + ","
            + "WeaponLocalPositionZ:" + WeaponLocalPositionZ + ","
            + "WeaponLocalEulerX:" + WeaponLocalEulerX + ","
            + "WeaponLocalEulerY:" + WeaponLocalEulerY + ","
            + "WeaponLocalEulerZ:" + WeaponLocalEulerZ + ","
            + "WeaponLocalScale:" + WeaponLocalScale + ","
            + "ProjectileSpeed:" + ProjectileSpeed + ","
            + "ProjectileDurationMs:" + ProjectileDurationMs + ","
            + "HitEffectDurationMs:" + HitEffectDurationMs + ","
            + "}";
        }

        partial void EndRef();
    }

}

